Added project Etch a skech in HTML Section
Sahani99/Mini-projects-Hacktoberfest2024 pull request #30
Opened 2024-10-26 05:22 UTC by jntbatra

Please merge it or mark it as "hacktoberfest-accepted" so that it counts towards my progress in Hacktoberfest
![image](https://github.com/user-attachments/assets/83fddcd6-c33a-4005-9d78-9b6085a13605)

2024-10-26 05:37 UTC, jntbatra commented
Please tag my previous as hacktoberfest-accepted as this is not showing up in my Hacktoberfest Dashboard i made changes so that the boxes don't push back

2024-10-26 06:31 UTC, Sahani99 approved these changes

2024-10-26 06:33 UTC, Sahani99 requested changes
there are conflicts with the main branch. resolve it please

2024-10-26 08:05 UTC, jntbatra commented
I have Done the requested changes and resolved the conflicts please merge

2024-10-27 04:05 UTC, Sahani99 approved these changes

2024-10-27 04:05 UTC, merged